# dokploy.yaml for Node.js Next.js app with automatic deploy on main branch

name: video-platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: dokploy/runner:latest
    steps:
      - uses: dokploy/actions/checkout@v1
      - uses: dokploy/actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm start
